baseURL = 'https://Vaibhav-sarvashreshth.github.io/blog/'
languageCode = 'en-us'
title = 'Vaibhav's Blogs'
theme = "m10c"

[params]
  author = "Christopher Hart"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/Vaibhav-sarvashreshth"

  

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"