baseURL = 'https://Vaibhav-sarvashreshth.github.io/blog/'
languageCode = 'en-us'
title = 'My New Hugo Site'


[params]
  author = "Christopher Hart"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/ChristopherJHart"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/_ChrisJHart"